# Generated by Django 4.0.5 on 2022-06-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fear', models.FloatField()),
                ('surprise', models.FloatField()),
                ('anger', models.FloatField()),
                ('sadness', models.FloatField()),
                ('neutrality', models.FloatField()),
                ('happiness', models.FloatField()),
                ('anxiety', models.FloatField()),
                ('embarrassed', models.FloatField()),
                ('hurt', models.FloatField()),
                ('interest', models.FloatField()),
                ('boredom', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'emotion_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InputSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_num', models.IntegerField()),
                ('sentence', models.CharField(max_length=512)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('done', models.IntegerField()),
            ],
            options={
                'db_table': 'input_sentence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('contact', models.CharField(max_length=13)),
                ('gender', models.CharField(max_length=4)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=45)),
                ('birth', models.DateField()),
                ('status', models.CharField(max_length=8)),
                ('specifics', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
